name: Parallel build

on: [push]

jobs:
  build-in-parallel:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Vim
        uses: thinca/action-setup-vim@v1
        with:
          vim_version: 'v8.2.0020'
          vim_type: 'Vim'
      - name: Generate new document
        run: |
          make -j2 html2
